CREATE TABLE IF NOT EXISTS projects(
    ID INT NOT NULL AUTO_INCREMENT,
    title TEXT NOT NULL ,
    description TEXT NOT NULL,
    url VARCHAR(64) NOT NULL,
    dateRegistered DATETIME DEFAULT CURRENT_TIMESTAMP,
    dateUpdated DATETIME ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (ID)
);