CREATE TABLE IF NOT EXISTS tags(
    ID INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(16) NOT NULL,
    colour VARCHAR(6) NOT NULL,
    dateRegistered DATETIME DEFAULT CURRENT_TIMESTAMP,
    dateUpdated DATETIME ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (ID)
);